### ISSUE TITLE
Error importing trftools

### ISSUE THREAD

**Issue by Doffff** [christianbrodbeck/Eelbrain#56]
Hi Christian,

I am trying to follow the analyses of the Alice dataset but I get this error when I try to import trftools. Maybe it happened to you before. Thanks in advance!

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[13], line 1
----> 1 import trftools

File [/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/trftools/__init__.py:6](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/trftools/__init__.py:6)
      4 from ._numpy_funcs import sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, arctanh
      5 from ._sound import gammatone_bank
----> 6 from .pipeline._eelfarm import start_dispatcher
      8 __version__ = '0.1.dev'

File [/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/trftools/pipeline/__init__.py:3](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/trftools/pipeline/__init__.py:3)
      1 # Author: Christian Brodbeck 
      2 from ._code import Code
----> 3 from ._experiment import TRFExperiment
      4 from ._jobs import TRFJob, TRFsJob, ModelJob, make_jobs, read_job_file
      5 from ._model import Term

File [/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/trftools/pipeline/_experiment.py:102](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/trftools/pipeline/_experiment.py:102)
    100 from eelbrain._experiment.mne_experiment import DataArg, PMinArg, DefinitionError, FileMissing, TestDims, Variables, guess_y, cache_valid
    101 from eelbrain._experiment.parc import SubParc
--> 102 from eelbrain._data_obj import NDVarArg, legal_dataset_key_re, isuv
    103 from eelbrain._io.pickle import update_subjects_dir
    104 from eelbrain._text import ms, n_of

ImportError: cannot import name 'legal_dataset_key_re' from 'eelbrain._data_obj' ([/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/eelbrain/_data_obj.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/eelbrain/lib/python3.11/site-packages/eelbrain/_data_obj.py))

**Comment by christianbrodbeck** [comment]
For now, use the previous version of Eelbrain (0.38.x)

**Comment by christianbrodbeck** [comment]
Closing this here because it's a trftools issue not Eelbrain
